version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Nothing to do in demo phase
  pre_build:
    commands:
      - echo Nothing in pre-build phase
  build:
    commands:
      - sudo chmod +x gradlew
      - echo Hello
      - ./gradlew clean build
  post_build:
    commands:
      - echo build completed in 'date'
artifacts:
  files:
    - build/libs/AwsDeploy-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml