version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Installing zip
          command: sudo apt-get install zip
      - run:
          name: Changing the file permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Building the app
          command: ./gradlew clean build
      - run:
          name: create a directory
          command: sudo mkdir innovation_ideas
      - run:
          name: Copy the contents
          command: cp build/libs/AwsDeploy-0.0.1-SNAPSHOT.jar innovation_ideas
      - persist_to_workspace:
          root: innovation_ideas
          paths:
            - AwsDeploy-0.0.1-SNAPSHOT.jar

#  test:
#    docker:
#      - image: cimg/<language>:<version TAG>
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#    steps:
#      - checkout
#      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
#      - test
