version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Installing zip
          command: sudo apt-get install zip
      - run:
          name: Changing the file permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Building the app
          command: ./gradlew clean build
      - run:
          name: Copy the contents
          command: ls -lrt
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/AwsDeploy-0.0.1-SNAPSHOT.jar
  test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Change permissions
          command: sudo chmod +x ./gradlew
      - run: ./gradlew test
  deploy:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - attach_workspace:
            at: .
      - run:
          name: Get the files
          command: ls -lrt
      - aws-s3/copy:
          from: build/libs/AwsDeploy-0.0.1-SNAPSHOT.jar
          to: 's3://circle-ci-demo/'
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
